### ISSUE TITLE
Unable to login. Says bad request.

### ISSUE THREAD

**Issue by karanrajpal14** [mattbdean/JRAW-Android#1]
As the title says, I'm unable to use the example app and login. It says that I've sent an invalid request. Any idea what's wrong? I'd appreciate it if you could resolve it or point me in the right direction.

**Comment by mattbdean** [comment]
Please post your code and the stacktrace

**Comment by karanrajpal14** [comment]
I'm sorry there was an issue with the redirect_url. Made a copy-paste error. I'll be closing this now.
