### ISSUE TITLE
Crashing upon login

### ISSUE THREAD

**Issue by karanrajpal14** [mattbdean/JRAW-Android#2]
The example app seems to be crashing off-late and I'm not quite sure why:

Here's the stacktrace:
```
09-07 21:46:39.665 15719-16197/rajpal.karan.unstash.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                            Process: rajpal.karan.unstash.debug, PID: 15719
                                                                            java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)
                                                                             Caused by: java.lang.IllegalStateException: Auth flow not started yet. See getAuthorizationUrl()
                                                                                at net.dean.jraw.http.oauth.OAuthHelper.onUserChallenge(OAuthHelper.java:130)
                                                                                at rajpal.karan.unstash.LoginActivity$2.doInBackground(LoginActivity.java:69)
                                                                                at rajpal.karan.unstash.LoginActivity$2.doInBackground(LoginActivity.java:64)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                at java.lang.Thread.run(Thread.java:761) 
```

I added some logging to see what the urls are:

```
D/LoginActivity: onCreate: 41 - auth url https://www.reddit.com/api/v1/authorize.compact?scope=identity+read+edit+flair+history+save+vote&response_type=code&state=n6ko8i149kfqude447cud8304g&redirect_uri=http%3A%2F%2Fwww.reddit.com&client_id=NaP7nvfW4D721A&duration=permanent
D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/api/v1/authorize.compact?scope=identity+read+edit+flair+history+save+vote&response_type=code&state=n6ko8i149kfqude447cud8304g&redirect_uri=http%3A%2F%2Fwww.reddit.com&client_id=NaP7nvfW4D721A&duration=permanent
D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/login.compact?dest=https%3A%2F%2Fwww.reddit.com%2Fapi%2Fv1%2Fauthorize.compact%3Fscope%3Didentity%2Bread%2Bedit%2Bflair%2Bhistory%2Bsave%2Bvote%26response_type%3Dcode%26state%3Dn6ko8i149kfqude447cud8304g%26redirect_uri%3Dhttp%253A%252F%252Fwww.reddit.com%26client_id%3DNaP7nvfW4D721A%26duration%3Dpermanent
D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/post/login.compact
D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/api/v1/authorize.compact?scope=identity+read+edit+flair+history+save+vote&response_type=code&state=n6ko8i149kfqude447cud8304g&redirect_uri=http%3A%2F%2Fwww.reddit.com&client_id=NaP7nvfW4D721A&duration=permanent
D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/api/v1/authorize
D/LoginActivity: onPageStarted: 48 - url http://www.reddit.com/?state=n6ko8i149kfqude447cud8304g&code=OurLM5eomgzvGdsb1OvF-x-naQ8
D/LoginActivity: doInBackground: 68 - url params 0 http://www.reddit.com/?state=n6ko8i149kfqude447cud8304g&code=OurLM5eomgzvGdsb1OvF-x-naQ8
D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/?state=n6ko8i149kfqude447cud8304g&code=OurLM5eomgzvGdsb1OvF-x-naQ8
D/LoginActivity: doInBackground: 68 - url params 0 https://www.reddit.com/?state=n6ko8i149kfqude447cud8304g&code=OurLM5eomgzvGdsb1OvF-x-naQ8
```

If I'm not wrong, the urls returned are correct but something else seems to be going wrong here. Any idea what's going on? Would you please have a look at this?
Maybe reddit changed something in their API? If you need any more help or logs, please do let me know. I just hope you can fix this as I'm working on an app that's using this login flow. I'd appreciate it of you could. Thank you @mattbdean !

**Comment by mattbdean** [comment]
This is most likely not an issue with the reddit API. The code that causes this exception is [here](https://github.com/mattbdean/JRAW/blob/v0.9.0/src/main/java/net/dean/jraw/http/oauth/OAuthHelper.java#L129-L131). Before you call `onUserChallenge` can you log `helper.getAuthStatus()`?

**Comment by karanrajpal14** [comment]
@mattbdean it says "WAITING_FOR_CHALLENGE"

**Comment by mattbdean** [comment]
If it was `WAITING_FOR_CHALLENGE` that exception wouldn't be thrown. The issue here is with the app logic. If I had to bet, I'd say you're calling `onAuthorizationUrl` *after* the client's already been authorized.

**Comment by karanrajpal14** [comment]
Well, like I said, I'm facing this issue just on your sample let aside my app which is using your code as is. Haven't made any changes since I don't understand what's going on there. Haven't added my code to that. I've only added some minimal logging that was needed for raising this issue. Something else might be going wrong here. Any idea what's up?

**Comment by karanrajpal14** [comment]
Why closed? Issue is still present.

**Comment by mattbdean** [comment]
Whoops, sorry. Forgot to save my comment.

Whenever the WebView starts to load a URL with a query parameter named `code` we call helper.onUserChallenge. From what I can tell reddit does some additional redirects whose URLs include that `code` paramter. Once the first onUserChallenge is complete, the helper's auth status is `AUTHORIZED`. That's why on the second call throws the error. Commit [`8f4523b`](https://github.com/mattbdean/JRAW-Android/commit/8f4523b5798850fd5219f6b93cc6d916dffc319c) fixes this.

**Comment by karanrajpal14** [comment]
@mattbdean Ah! Makes sense. Thank you, both, for the explanation and fixing the issue!

**Comment by mattbdean** [comment]
Sure thing, let me know if you find anything else

**Comment by nepalauziamas** [comment]
> The example app seems to be crashing off-late and I'm not quite sure why:
> 
> Here's the stacktrace:
> 
> ```
> 09-07 21:46:39.665 15719-16197/rajpal.karan.unstash.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
>                                                                             Process: rajpal.karan.unstash.debug, PID: 15719
>                                                                             java.lang.RuntimeException: An error occurred while executing doInBackground()
>                                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:325)
>                                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
>                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                                                 at java.lang.Thread.run(Thread.java:761)
>                                                                              Caused by: java.lang.IllegalStateException: Auth flow not started yet. See getAuthorizationUrl()
>                                                                                 at net.dean.jraw.http.oauth.OAuthHelper.onUserChallenge(OAuthHelper.java:130)
>                                                                                 at rajpal.karan.unstash.LoginActivity$2.doInBackground(LoginActivity.java:69)
>                                                                                 at rajpal.karan.unstash.LoginActivity$2.doInBackground(LoginActivity.java:64)
>                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:305)
>                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
>                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
>                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
>                                                                                 at java.lang.Thread.run(Thread.java:761) 
> ```
> 
> I added some logging to see what the urls are:
> 
> ```
> D/LoginActivity: onCreate: 41 - auth url https://www.reddit.com/api/v1/authorize.compact?scope=identity+read+edit+flair+history+save+vote&response_type=code&state=n6ko8i149kfqude447cud8304g&redirect_uri=http%3A%2F%2Fwww.reddit.com&client_id=NaP7nvfW4D721A&duration=permanent
> D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/api/v1/authorize.compact?scope=identity+read+edit+flair+history+save+vote&response_type=code&state=n6ko8i149kfqude447cud8304g&redirect_uri=http%3A%2F%2Fwww.reddit.com&client_id=NaP7nvfW4D721A&duration=permanent
> D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/login.compact?dest=https%3A%2F%2Fwww.reddit.com%2Fapi%2Fv1%2Fauthorize.compact%3Fscope%3Didentity%2Bread%2Bedit%2Bflair%2Bhistory%2Bsave%2Bvote%26response_type%3Dcode%26state%3Dn6ko8i149kfqude447cud8304g%26redirect_uri%3Dhttp%253A%252F%252Fwww.reddit.com%26client_id%3DNaP7nvfW4D721A%26duration%3Dpermanent
> D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/post/login.compact
> D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/api/v1/authorize.compact?scope=identity+read+edit+flair+history+save+vote&response_type=code&state=n6ko8i149kfqude447cud8304g&redirect_uri=http%3A%2F%2Fwww.reddit.com&client_id=NaP7nvfW4D721A&duration=permanent
> D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/api/v1/authorize
> D/LoginActivity: onPageStarted: 48 - url http://www.reddit.com/?state=n6ko8i149kfqude447cud8304g&code=OurLM5eomgzvGdsb1OvF-x-naQ8
> D/LoginActivity: doInBackground: 68 - url params 0 http://www.reddit.com/?state=n6ko8i149kfqude447cud8304g&code=OurLM5eomgzvGdsb1OvF-x-naQ8
> D/LoginActivity: onPageStarted: 48 - url https://www.reddit.com/?state=n6ko8i149kfqude447cud8304g&code=OurLM5eomgzvGdsb1OvF-x-naQ8
> D/LoginActivity: doInBackground: 68 - url params 0 https://www.reddit.com/?state=n6ko8i149kfqude447cud8304g&code=OurLM5eomgzvGdsb1OvF-x-naQ8
> ```
> 
> If I'm not wrong, the urls returned are correct but something else seems to be going wrong here. Any idea what's going on? Would you please have a look at this? Maybe reddit changed something in their API? If you need any more help or logs, please do let me know. I just hope you can fix this as I'm working on an app that's using this login flow. I'd appreciate it of you could. Thank you @mattbdean !
